# Generated by Django 5.1.4 on 2025-03-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('OFFICER', 'Enrollment Officer'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
