# Generated by Django 5.1.4 on 2025-03-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofile_program'),
    ]

    operations = [
    ]
