# Generated by Django 5.1.4 on 2025-03-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250312_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.CharField(max_length=100),
        ),
    ]
