# Generated by Django 5.1.3 on 2025-03-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='When registration starts')),
                ('end_date', models.DateTimeField(help_text='When registration ends')),
                ('is_open', models.BooleanField(default=False, help_text='Indicates if registration is currently open')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_class_time', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text="Student's preferred class time", max_length=2)),
                ('preferred_section', models.CharField(help_text="Student's preferred section (e.g., A, B, C)", max_length=20)),
                ('minor_subjects_chosen', models.PositiveIntegerField(default=0, help_text='Number of minor subjects chosen by the student')),
                ('additional_comments', models.TextField(blank=True, help_text='Any additional information provided by the student', null=True)),
                ('officer_notes', models.TextField(blank=True, help_text='Notes or modifications by the officer regarding registration details', null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False, help_text='Indicates if the registration process is completed')),
                ('registration_form_image', models.ImageField(blank=True, help_text='PNG file of the final registration form uploaded by the officer', null=True, upload_to='registration_forms/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.studentprofile')),
            ],
        ),
    ]
