# Generated by Django 5.1.3 on 2025-03-30 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationwindow',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='When registration ends (Time only)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrationwindow',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='When registration starts (Time only)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrationwindow',
            name='end_date',
            field=models.DateField(help_text='When registration ends (Date only)'),
        ),
        migrations.AlterField(
            model_name='registrationwindow',
            name='start_date',
            field=models.DateField(help_text='When registration starts (Date only)'),
        ),
    ]
