# Generated by Django 5.1.4 on 2025-03-22 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0007_delete_studentsubjectchecklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False, help_text='Indicates if the student has taken the subject.')),
                ('taken_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_checklists', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_checklists', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Student Subject Checklist',
                'verbose_name_plural': 'Student Subject Checklists',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
