# Generated by Django 5.1.3 on 2025-03-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('studentSubjectCheckList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjectchecklist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_checklists', to='accounts.studentprofile'),
        ),
    ]
