# Generated by Django 5.1.4 on 2025-03-22 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('subject_type', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=10)),
                ('year_level', models.PositiveIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Applicable for major subjects only', null=True)),
                ('units', models.PositiveIntegerField(default=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.department')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Select prerequisite subjects (if any)', related_name='dependent_subjects', to='subjects.subject')),
                ('programs', models.ManyToManyField(blank=True, help_text='Select programs for which this subject is offered', related_name='subjects', to='accounts.program')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('taken_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_checklists', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_checklists', to='subjects.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
