# Generated by Django 5.1.4 on 2025-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lab_units',
            field=models.PositiveIntegerField(default=0, help_text='Laboratory units'),
        ),
        migrations.AddField(
            model_name='subject',
            name='lec_units',
            field=models.PositiveIntegerField(default=3, help_text='Lecture units'),
        ),
    ]
