# Generated by Django 5.1.4 on 2025-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_lab_units_subject_lec_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=30),
        ),
    ]
