# Generated by Django 5.1.4 on 2025-03-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_subject_department_subject_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('1st', '1st Semester'), ('2nd', '2nd Semester')], default='1st', max_length=30),
        ),
    ]
