# Generated by Django 5.1.4 on 2025-03-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('1st', '1st Semester'), ('2nd', '2nd Semester')], default='--', max_length=30),
        ),
    ]
