# Generated by Django 5.1.4 on 2025-03-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubjectChecklist',
        ),
    ]
