# Generated by Django 5.1.3 on 2025-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_delete_studentsubjectchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
